### ISSUE TITLE
Initializing the index: 'nycjobs'

### ISSUE THREAD

**Issue by edteke** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#1]
Great sample and great job!

When running this sample locally, after updating web.config with the proper SearchServiceName and SearchServiceApiKey for an Azure Search service I just created I get error because there is not index created yet. Make sense.

**Q**: How to create the index in that search service for the same sample data from NYC Open Data Initiative?

Can this be included in the repo too so people trying to run this sample will have also instructions/scripts to create the index and populate them with proper data?

Thanks

**Comment by liamca** [comment]
Hi, and yes, this makes sense.  I will try to upload a version that loads this data for you.  In the meantime, you can use the following service: azs-playground along with this query api-key: 252044BE3886FE4A8E3BAA4F595114BB to test the application code.
