### ISSUE TITLE
Bing key in Web config

### ISSUE THREAD

**Issue by paulinetheitgirl** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#10]
Should be
`<!--<add key="BingApiKey" value="[Bing API Key]" />-->`
Otherwise it doesn't launch in VS2017

**Comment by bitsforthought** [comment]
Sorry we missed this. We'll use this issue to track it: https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/issues/13
