### ISSUE TITLE
Typo bug in index.cshml

### ISSUE THREAD

**Issue by rdenisyuk** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#11]
You may have noticed that the search result count of the initial page load is different from any subsequent request with no search values/filters. Wonder why? There is a typo in index.cshml in the UpdateFilterReset function:

if ((businessTitleFacet != '') || (postingTypeFacet != '') || **(salaryRangeFacet |= ''))**

The != operator is replaced with |= that modifies the content of salaryRangeFacet

**Comment by bitsforthought** [comment]
FYI @liamca

**Comment by liamca** [comment]
Thank-you for finding this typo.  Fix has been applied.
