### ISSUE TITLE
Update bing key in demo

### ISSUE THREAD

**Issue by amrlafi** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#13]
Bing key in the demo website has expired.

**Comment by bitsforthought** [comment]
FYI @liamca

**Comment by liamca** [comment]
Key has been updated, however, there is an issue viewing map in Chrome as outlined in [issue #16](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/issues/16).  For that reason, I am closing this, but will leave Issue #16 open till it has been fixed.
