### ISSUE TITLE
Still using typeahead?

### ISSUE THREAD

**Issue by virasana** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#14]
Hello, 

The code in index.cshtml  uses the typeahead class on the input element:

`<input type="submit" class="**typeahead** search-submit" value=" " onclick="Search();">`

Is typeahead still being used (it looks like you are using jquery-ui  .autocomplete instead.  

Suggested solution:  remove the **typeahead** class above.  

The code is confusing because [this](https://azure.microsoft.com/en-gb/blog/azure-search-how-to-add-suggestions-auto-complete-to-your-search-applications/) article refers to typeahead, indirectly referencing this repo...

**Comment by bitsforthought** [comment]
FYI @liamca

**Comment by liamca** [comment]
Thanks for the PR.  I will try to look at this later this week.
