### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by paulinetheitgirl** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#16]
The map on the index page used to load fine for me, but now requires this change:
[https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/commit/1c6f429f065a405229f8b8519db63d1318aeeb94](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/commit/1c6f429f065a405229f8b8519db63d1318aeeb94)
otherwise I get a script error and the map is not displayed.

**Comment by liamca** [comment]
@paulinetheitgirl - I have deployed a fix.  It would be great if you could confirm it shows the map for you.

**Comment by paulinetheitgirl** [comment]
Works perfectly! Thanks @liamca
