### ISSUE TITLE
Question: How to load json data to index?

### ISSUE THREAD

**Issue by chaliy** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#2]
Hello,

Do you have any instructions or suggestions how to load data from Schema_and_Data to actual index? Do you use some scripts?

**Comment by liamca** [comment]
Hi Chaliy,  the schema and data can be found [here](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/tree/master/NYCJobsWeb/Schema_and_Data).  Please let me know if you have any issues with getting it loaded.

**Comment by liamca** [comment]
I have added a sample that loads both the ZipCodes and Jobs data into Azure Search indexes.  This can be [found here](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/tree/master/DataLoader).
