### ISSUE TITLE
Using the facet filter in a solution .NET

### ISSUE THREAD

**Issue by mau1133** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#7]
Hi,

The solution is great. I am trying to install that for my project, but I am know about C# and .CSHTML and I do not know about JavaScript. 

Where do you set the fields from the azure search index? For instance,  I need mapping 'AcademicTitle' from my azure search index with the Textbox. 

Thanks,

Best Regards

**Comment by bitsforthought** [comment]
@mau1133 Could you clarify what you're trying to do? It sounds like you want to know how to render document fields on your results page using JavaScript... is that right?

**Comment by mau1133** [comment]
yes, I need to mapping the index fields with the results page using the javascript code that you have shared.

Thanks

**Comment by liamca** [comment]
@mau1133 the way this works for this project is that the [index.cshtml](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/blob/master/NYCJobsWeb/Views/Home/Index.cshtml) file contains the JavaScript code to show the results of the Azure Search query in HTML (using JavaScript).  You will see in this file how a JQuery Post is made to /home/search whenever a search is requested.  This makes a call to the Search function in the [HomeController.cs](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/blob/master/NYCJobsWeb/Controllers/HomeController.cs) which actually executes the search and then returns the values to the client in the JavaScript code to be visualized,

Hope that helps.
