### ISSUE TITLE
How to fill search

### ISSUE THREAD

**Issue by uuuus** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#8]
Hi,

I see, that I have to set my SearchServiceName, SearchServiceApiKey and BingApiKey. But how to fill search with data? 

thanks!
Slawomir

**Comment by bitsforthought** [comment]
@uuuus You can populate the search service with data using the [DataLoader project](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/tree/master/DataLoader).
